name: Release

on:
  workflow_dispatch:
  push:
    tags:
    - 'v*'

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-24.04, windows-2022, macos-13, macos-latest]
        include:
          - os: ubuntu-24.04
            goos: linux
            suffix: linux-amd64
          - os: windows-2022
            goos: windows
            suffix: windows-amd64
          - os: macos-13
            goos: darwin
            suffix: osx-amd64
          - os: macos-latest
            goos: darwin
            suffix: osx-arm64

    steps:
      - uses: actions/checkout@main
      - uses: actions-rust-lang/setup-rust-toolchain@v1
      - uses: actions/setup-python@v5
        with:
          python-version: '3.13'
      - run: sudo apt update && sudo apt install -y libasound2-dev pkg-config
        if: matrix.goos == 'linux'
      - name: build
        run: python release.py
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.suffix }}
          path: work-timer-${{ matrix.suffix }}.*

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download Artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts
      - name: Create Release
        uses: softprops/action-gh-release@v2
        if: github.ref_type == 'tag'
        with:
          files: artifacts/*/*
